# Jekyll Resume Theme

# Site settings
title: Nicole Zhang
email: nzhang@cmmt.ubc.ca
description: Deep learning, Evolution, Molecular Biology
baseurl: "https://nzhangx.github.io./"
url: "https://nzhangx.github.io./"
name: Nicole Zhang
job: Masters Student in Bioinformatics
location: Vancouver, Canada
languages: Python, R, Bash, Java
twitter_username: NZhang211
github_username:  nZhangx
#codepen_username:  mattcouchman
email_address: nzhang@cmmt.ubc.ca

# Build settings
markdown: kramdown
